"""Remove temporary column

Revision ID: 072076761a4a
Revises: f31e840a5e3d
Create Date: 2025-03-08 16:21:15.457598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072076761a4a'
down_revision = 'f31e840a5e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
