"""Allow NULL access_token in User table

Revision ID: 17baa9919749
Revises: e356b6587276
Create Date: 2025-03-06 21:04:59.663675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17baa9919749'
down_revision = 'e356b6587276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
