"""Recreating migrations with shopify_domain

Revision ID: 8a4ee1c32fb7
Revises: 
Create Date: 2025-03-04 20:53:57.003472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer, String, Boolean

# revision identifiers, used by Alembic.
revision = '8a4ee1c32fb7'
down_revision = None
branch_labels = None
depends_on = None


from sqlalchemy import Column, Integer, String, Boolean

def upgrade():
    op.create_table(
        'user',
        Column('id', Integer, primary_key=True),
        Column('email', String(120), unique=True, nullable=False),
        Column('password_hash', String(128), nullable=False),
        Column('shopify_domain', String(255), unique=True, nullable=True),
        Column('access_token', String(255), nullable=True),
        Column('is_active', Boolean, default=True)
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopify_domain', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
