"""Allow null password_hash for OAuth users

Revision ID: 934130bfdc8a
Revises: e35a20d354e8
Create Date: 2025-03-08 19:36:35.513458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934130bfdc8a'
down_revision = 'e35a20d354e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
