"""Add FTP settings to User model

Revision ID: b52b834fbb92
Revises: 4826a9cbd5bc
Create Date: 2025-03-02 20:22:20.966933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52b834fbb92'
down_revision = '4826a9cbd5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_host', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ftp_user', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ftp_pass', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ftp_pass')
        batch_op.drop_column('ftp_user')
        batch_op.drop_column('ftp_host')

    # ### end Alembic commands ###
